Repository algorand/go-algorand-sdk, pull requests merged in 2022-08, with the labels that each got.

#345 AVM: Consolidate TEAL and AVM versions
  logic/logic.go
  logic/logic_test.go
Labels: Enhancement

#349 Testing: Use Dev mode network for cucumber tests
  Makefile
  test/applications_integration_test.go
  test/steps_test.go
Labels: Enhancement

#352 AVM: Use avm-abi repo
  abi/abi.go
  abi/abi_test.go
  abi/interactions.go
  go.mod
  go.sum
Labels: Enhancement

#363 FOR REVIEW ONLY - go-algorand-sdk v1.19.0
  CHANGELOG.md
  Makefile
  abi/abi.go
  abi/abi_test.go
  abi/interactions.go
  go.mod
  go.sum
  logic/logic.go
  logic/logic_test.go
  test/applications_integration_test.go
  test/steps_test.go
Labels: Team Hyper Flow

#360 Enhancement: Use Sandbox for Testing
  .test-env
  Makefile
  README.md
  test-harness.sh
  test/algodclientv2_test.go
  test/applications_integration_test.go
  test/applications_unit_test.go
  test/docker/run_docker.sh
  test/docker/sdk.py
  test/helpers.go
  test/indexer_integration_test.go
  test/indexer_unit_test.go
  test/integration.tags
  test/steps_test.go
  test/transactions_test.go
  test/unit.tags
Labels: Enhancement

#371 Bug-Fix: passthru verbosity
  test-harness.sh
Labels: Bug-Fix

#366 Enhancement: Deprecating use of langspec
  crypto/account.go
  crypto/crypto.go
  crypto/crypto_test.go
  logic/logic.go
  test/steps_test.go
  test/unit.tags
Labels: Enhancement

#374 StateProof: State proof support
  client/v2/algod/algod.go
  client/v2/algod/getLightBlockHeaderProof.go
  client/v2/algod/getStateProof.go
  client/v2/algod/getTransactionProof.go
  client/v2/common/models/block.go
  client/v2/common/models/hash_factory.go
  client/v2/common/models/indexer_state_proof_message.go
  client/v2/common/models/light_block_header_proof.go
  client/v2/common/models/merkle_array_proof.go
  client/v2/common/models/state_proof.go
  client/v2/common/models/state_proof_fields.go
  client/v2/common/models/state_proof_message.go
  client/v2/common/models/state_proof_participant.go
  client/v2/common/models/state_proof_reveal.go
  client/v2/common/models/state_proof_sig_slot.go
  client/v2/common/models/state_proof_signature.go
  client/v2/common/models/state_proof_tracking.go
  client/v2/common/models/state_proof_verifier.go
  client/v2/common/models/transaction.go
  client/v2/common/models/transaction_proof_response.go
  client/v2/common/models/transaction_state_proof.go
  test/algodclientv2_test.go
  test/responses_unit_test.go
  types/basics.go
  types/block.go
  types/stateproof.go
  types/transaction.go
Labels: New Feature

#378 State Proofs: Use generic type for StateProof txn field.
  types/block.go
  types/stateproof.go
Labels: Enhancement

#370 BugFix: Src map type assert fix
  logic/source_map.go
Labels: Bug-Fix

#380 Improvement: Better SourceMap decoding
  logic/source_map.go
Labels: Enhancement

#377 StateProof: State Proof Verification additions
  .circleci/config.yml
  crypto/crypto.go
  go.mod
  go.sum
  types/lightBlockHeader.go
  types/stateproof.go
Labels: Team Sphinx, New Feature
