Repository algorand/go-algorand-sdk, pull requests merged in 2022-09, with the labels that each got.

#382 State Proofs: added compute leaf function for light block header to sdk
  crypto/crypto.go
Labels: Team Sphinx, New Feature

#383 State Proofs: renamed light block header hash func
  crypto/crypto.go
Labels: Team Sphinx, New Feature

#386 tests: Enable stpf cucumber unit tests
  test/unit.tags
Labels: Enhancement

#401 enhancement: update block model
  client/v2/common/models/block.go
  client/v2/common/models/participation_updates.go
  client/v2/indexer/searchForAccounts.go
  test/unit.tags
Labels: Enhancement, Team Lamprey

#400 BugFix: Fix dryrun parser
  future/dryrun.go
Labels: Bug-Fix
