Repository algorand/go-algorand-sdk, pull requests merged in 2023-08, with the labels that each got.

#591 Text: Fix pre-release-version description in create-release-pr workflow
  .github/workflows/create-release-pr.yml
Labels: Team Hyper Flow, Skip-Release-Notes

#595 types: Reject non canonical addresses in DecodeAddress
  types/address.go
  types/address_test.go
Labels: Team Lamprey, Bug-Fix

#603 consensus config: add dynamic filter timeout parameter
  protocol/config/consensus.go
Labels: Enhancement
