Repository algorand/go-algorand-sdk, pull requests merged in 2023-05, with the labels that each got.

#524 DevOps: Add CODEOWNERS to restrict workflow editing
  .github/workflows/pr-type-category.yml
  CODEOWNERS
Labels: Enhancement

#523 Performance: Add custom http transport to MakeClientWithTransport
  client/v2/common/common_test.go
Labels: Enhancement

#531 bugfix: adding EvalDelta.SharedAccts
  types/block.go
Labels: Bug-Fix

#533 DevOps: Update CODEOWNERS to only refer to the devops group
  CODEOWNERS
Labels: Enhancement, Unplanned, Team Hyper Flow

#534 lint: Add `golangci-lint` to CI process
  .github/workflows/reviewdog.yml
  .golangci.yml
  Makefile
  README.md
  client/v2/algod/rawTransaction.go
  test/utilities.go
  transaction/transaction_test.go
  types/basics.go
Labels: Enhancement

#542 Docs: update README to include a pointer to the testing repo
  README.md
Labels: Skip-Release-Notes

#538 algod: State delta endpoints
  .golangci.yml
  client/v2/algod/algod.go
  client/v2/algod/getLedgerStateDelta.go
  client/v2/algod/getLedgerStateDeltaForTransactionGroup.go
  client/v2/algod/getTransactionGroupLedgerStateDeltasForRound.go
  client/v2/common/models/ledger_state_delta_for_transaction_group.go
  client/v2/common/models/transaction_group_ledger_state_deltas_for_round_response.go
  test/algodclientv2_test.go
  test/responses_unit_test.go
  test/unit.tags
Labels: Enhancement

#540 enhancement: Verbose Test Harness
  .test-env
  README.md
Labels: Enhancement

#543 types: add consensus protocol and types.
  protocol/config/consensus.go
  protocol/consensus.go
Labels: Enhancement
