Repository algorand/go-algorand-sdk, pull requests merged in 2023-06, with the labels that each got.

#553 clients: Regenerate client.
  client/v2/algod/getLedgerStateDelta.go
  client/v2/algod/getLedgerStateDeltaForTransactionGroup.go
  client/v2/algod/getTransactionGroupLedgerStateDeltasForRound.go
  test/unit.tags
  test/utilities.go
Labels: Enhancement, Team Lamprey

#555 CICD: Add github action create-release-pr workflow
  .github/workflows/create-release-pr.yml
Labels: Team Hyper Flow, Skip-Release-Notes

#559 docs: Readme fixes
  README.md
Labels: Enhancement

#560 encoder: Update go-codec version.
  .circleci/config.yml
  encoding/json/json_test.go
  go.mod
  go.sum
  test/docker/Dockerfile
Labels: Enhancement

#566 Build: Go 1.20 and golint-ci 1.52 support
  .circleci/config.yml
  .github/workflows/codegen.yml
  .github/workflows/create-release-pr.yml
  .github/workflows/reviewdog.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  protocol/config/consensus.go
  test/helpers.go
  test/utilities.go
  transaction/transaction.go
  transaction/transactionSigner.go
  transaction/waitForConfirmation.go
  types/applications.go
  types/block.go
  types/statedelta.go
  types/stateproof.go
Labels: New Feature
