Repository algorand/go-algorand-sdk, pull requests merged in 2023-01, with the labels that each got.

#443 enhancement: add genesis type
  types/genesis.go
  types/genesis_test.go
  types/test_resource/mainnet_genesis.json
Labels: Enhancement, Team Lamprey

#460 docs: Update README.md
  README.md
Labels: Enhancement

#461 bugfix: Fix wrong response error type.
  client/v2/common/common.go
Labels: Team Lamprey, Bug-Fix

#462 tests: Add disassembly test for Go SDK
  test/integration.tags
  test/steps_test.go
Labels: Enhancement
