Repository algorand/go-algorand-sdk, pull requests merged in 2025-05, with the labels that each got.

#706 Txns: App versioning
  protocol/config/consensus.go
  types/applications.go
  types/statedelta.go
  types/transaction.go
Labels: Enhancement

#717 Chore: Remove unneeded allocbounds from SDK
  protocol/config/consensus.go
  types/asset.go
Labels: Enhancement

#719 API: Test updates to exercise API changes going out in go-algorand 4.1.x.
  test/algodclientv2_test.go
  test/indexer_unit_test.go
Labels: Skip-Release-Notes

#726 API: Revert application boxes pagination
  client/v2/algod/getApplicationBoxes.go
  test/algodclientv2_test.go
Labels: Bug-Fix
